services:
  - type: web
    name: zyora-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
    autoDeploy: true
